/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmIdRouteImport } from './routes/dm.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppChatsRouteImport } from './routes/_app.chats'

const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmIdRoute = DmIdRouteImport.update({
  id: '/dm/$id',
  path: '/dm/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/seed': typeof SeedRoute
  '/chats': typeof AppChatsRoute
  '/create': typeof AppCreateRoute
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/activity/$id': typeof ActivityIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/dm/$id': typeof DmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/seed': typeof SeedRoute
  '/chats': typeof AppChatsRoute
  '/create': typeof AppCreateRoute
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/activity/$id': typeof ActivityIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/dm/$id': typeof DmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/seed': typeof SeedRoute
  '/_app/chats': typeof AppChatsRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/map': typeof AppMapRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/activity/$id': typeof ActivityIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/dm/$id': typeof DmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/seed'
    | '/chats'
    | '/create'
    | '/home'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/activity/$id'
    | '/chat/$id'
    | '/dm/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/seed'
    | '/chats'
    | '/create'
    | '/home'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/activity/$id'
    | '/chat/$id'
    | '/dm/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/seed'
    | '/_app/chats'
    | '/_app/create'
    | '/_app/home'
    | '/_app/map'
    | '/_app/notifications'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/settings'
    | '/activity/$id'
    | '/chat/$id'
    | '/dm/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  SeedRoute: typeof SeedRoute
  ActivityIdRoute: typeof ActivityIdRoute
  ChatIdRoute: typeof ChatIdRoute
  DmIdRoute: typeof DmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$id': {
      id: '/dm/$id'
      path: '/dm/$id'
      fullPath: '/dm/$id'
      preLoaderRoute: typeof DmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatsRoute: typeof AppChatsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMapRoute: typeof AppMapRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatsRoute: AppChatsRoute,
  AppCreateRoute: AppCreateRoute,
  AppHomeRoute: AppHomeRoute,
  AppMapRoute: AppMapRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  SeedRoute: SeedRoute,
  ActivityIdRoute: ActivityIdRoute,
  ChatIdRoute: ChatIdRoute,
  DmIdRoute: DmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
